# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-27 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infection_rate', models.FloatField(null=True)),
                ('recovery_rate', models.FloatField(null=True)),
                ('upload_file', models.FileField(upload_to='useruploadedfiles')),
            ],
        ),
    ]
