# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-27 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20180627_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('counter', models.IntegerField(null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='parameters',
            name='upload_file',
            field=models.FileField(upload_to='profile_pics'),
        ),
    ]
